main: com.coco.CombatLog
name: CombatLog
api-version: 1.13
version: 1.0.0
author: coco
description: Combat log plugin
softdepend:
  - Multiverse-Core
commands:
  lightcombatlog:
    description: reloads plugin
